version: '3.1'
services:
  php-fpm:
    build: docker/php-fpm
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - '.:/var/www/html'
      - './docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'

  nginx:
    image: 'nginx:1.23.3-alpine'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - nginx-proxy-manager
      - default
  mysql:
    image: 'mysql:8.0'
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$dbrootpw
      - MYSQL_DATABASE=$dbname
      - MYSQL_USER=$dbuser
      - MYSQL_PASSWORD=$dbpw

  mailpit:
    image: 'axllent/mailpit:v1.7'

  swagger-ui:
    platform: linux/amd64
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
volumes:
  db:
networks:
  nginx-proxy-manager:
    external: true
