version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=$dbpw
            - MYSQL_DATABASE=$dbdb
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        networks:
          - nginx-proxy-manager
        volumes:
            - ../:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
networks:
  nginx-proxy-manager:
    external: true
volumes:
  db:
  
